version: "3"
services:
  web:
    image: marcofaggian/randomic-rabbit-web
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    image: marcofaggian/randomic-rabbit-server
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - redis
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
volumes:
  postgres:
